dependencies:
  - python=3.8
  - pip
  - pip:
    - requests
    - peekingduck
    - beautifulsoup4==4.11.2
    - opencv-python==4.7.0.68
    - pandas==1.5.3
    - numpy==1.24.2
    - huggingface_hub==0.12.0
    - datasets>= 2.8