dependencies:
  - python=3.8
  - pip
  - pip:
    - requests
    - peekingduck==1.3.0.post1
    - beautifulsoup4==4.11.2
    - opencv-python==4.7.0.68
    - pandas==1.5.3
    - numpy==1.24.2
    - scikit-image
    - typeguard==2.13.3