name: GetCounts

on:
# for now, disable schedule
#   schedule:
#     - cron: "0 4 * * *"
  workflow_dispatch:
  
jobs:
  get-counts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set Timezone
      uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Singapore"
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install requirements
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        conda env update --file environment.yml --name base
    - name: Run Scraper
      run: |
        python -m src.main
    - name: Commit and push
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add data/counts_dataset.csv  # or git add -A to add all files
        git commit -m "Updated counts_dataset.csv"
        git push "https://${GITHUB_ACTOR}:${TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main || exit 0
